# Generated by Django 3.2.13 on 2022-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleitem',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
